# Generated by Django 4.1.11 on 2023-10-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(upload_to='thumbnails/')),
                ('image', models.ImageField(upload_to='images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
