# Generated by Django 4.1.11 on 2023-10-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app1',
            name='thumbnail',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='thumbnails/'),
        ),
    ]
